[workspace]
members = ["crates/*", "apps/desktop/src-tauri"]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"