// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the name and version of an MCP implementation, with an optional title for UI representation.
 */
export type Implementation = { name: string, title?: string | null, version: string, user_agent?: string | null, };
