// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Implementation } from "./Implementation";
import type { ServerCapabilities } from "./ServerCapabilities";

/**
 * After receiving an initialize request from the client, the server sends this response.
 */
export type InitializeResult = { capabilities: ServerCapabilities, instructions?: string | null, protocolVersion: string, serverInfo: Implementation, };
