// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Present if the server offers any prompt templates.
 */
export type ServerCapabilitiesPrompts = { listChanged?: boolean | null, };
