// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerCapabilitiesPrompts } from "./ServerCapabilitiesPrompts";
import type { ServerCapabilitiesResources } from "./ServerCapabilitiesResources";
import type { ServerCapabilitiesTools } from "./ServerCapabilitiesTools";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Capabilities that a server may support. Known capabilities are defined here, in this schema, but this is not a closed set: any server can define its own, additional capabilities.
 */
export type ServerCapabilities = { completions?: JsonValue | null, experimental?: JsonValue | null, logging?: JsonValue | null, prompts?: ServerCapabilitiesPrompts | null, resources?: ServerCapabilitiesResources | null, tools?: ServerCapabilitiesTools | null, };
